### ISSUE TITLE
Toggling between card & bank payment methods appends duplicate form fields to the DOM

### ISSUE THREAD

**Issue by jmanlapid** [gettilled/tilled-example-monorepo#10]
## Reproduction steps
1. Run the react-payment-example
2. Click [Bank Transfer]
3. Click [Credit Card]
4. Notice how there is more than 1 set of credit card fields attached to the DOM. Pressing tab on the keyboard will stay on the field, if there is a duplicate, instead of moving to the next field

## Expected behavior
Only one set of payment method forms should be rendered in the DOM at a time

https://user-images.githubusercontent.com/5409443/205398199-0a6e234f-9460-4b97-8d4f-30cb036d1f55.mp4

**Comment by dpatton1992** [comment]
Hey James, I am currently working on a ticket to refactor this example. I plan to move the Tilled.js logic into the [CreditCardFields](https://github.com/gettilled/tilled-example-monorepo/blob/master/react-payment-example/client/src/Components/credit-card-fields.js) and [AchDebitFIelds](https://github.com/gettilled/tilled-example-monorepo/blob/master/react-payment-example/client/src/Components/ach-debit-fields.js) components. I will also load the tilled.js script dynamically when these components mount and run the [teardown method](https://docs.tilled.com/tilledjs/#formteardownhandler-promiseboolean--void) when they unmount. 

If I cannot get the teardown invocation to work with strict mode, I will document the issue and work with Engineering on a solution.

**Comment by dpatton1992** [comment]
Hey James,

This was fixed with this [PR](https://github.com/gettilled/tilled-example-monorepo/pull/11). I also successfully tested it with Strict Mode. I did a lot of refactoring as well and moved all the tilled.js logic into a custom hook. The documentation is in the readme.
