### ISSUE TITLE
React tilled version- clean up issues

### ISSUE THREAD

**Issue by imtmh** [gettilled/tilled-example-monorepo#121]
I am facing issues with elements being injected multiple tiles(ex: card number is  injected multiple times into the dom)

My code is almost same as the following repo:
https://github.com/jmanlapid/tilledjs-react

Any help regarding the cleanup is appreciated/

**Comment by dpatton1992** [comment]
Hello @imtmh! Have you tried looping through and deleting old iframes when your component renders? See this [example](whsec_1V4WuIeddESrLDWanUZAsSKzoqgyIZwK).

Looking at the link you provided, it seems like the tilled instance is created in the window as a global in the DOM, meaning that its state will persist even after the component dismounts and is removed from React's virtual DOM. You will need to either keep track of the tilled instance in a parent component as a ref or use a state management library like Zustand or Redux. If you need more guidance, please reach out to integrations@tilled.com
